spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: 
      secret-key: 
      oss:
        bucket: glmall-binggr
        endpoint: oss-cn-chengdu.aliyuncs.com
      sms:
        host: https://feginesms.market.alicloudapi.com
        path: /codeNotice
        skin: 1
        sign: 1
        appcode: ba9a1ad0812341f18f4d862400034960

  application:
    name: glmall-third-party

server:
  port: 30000


